### ISSUE TITLE
Error when using query strings.

### ISSUE THREAD

**Issue by zyxxyzyxz** [tabuna/breadcrumbs#12]
I use Livewire, and take advantage of their query string functionality.

Whenever a query string is set, the breadcrumb package interrupts and adds a really long query string. No idea why this happens.
![image](https://user-images.githubusercontent.com/22277786/93433482-6c8dd100-f8f9-11ea-8b48-878cacfa274d.png)

**Comment by tabuna** [comment]
Hey @zyxxyzyxz. Can you attach some code so that I can reproduce this?

**Comment by zyxxyzyxz** [comment]
@tabuna 

```php
class Index extends Component
{
    public $month;
    public $year;

    protected $queryString = [
        'month',
        'year'
    ];

    public function mount()
    {
        $this->month = request()->query('month') ?? 9;
        $this->year = request()->query('year') ?? 2020;
    }

    public function render()
    {
        return view('livewire.component.index');
    }
}
```

`livewire.component.index` is just a blank view. Breadcrumb would look like below;
```php
Route::get('/component', \App\Http\Livewire\Component\Index::class)
            ->name('component.index')
            ->breadcrumbs(fn (Trail $trail) => $trail->parent('component.parent')->push('Component Index', route('component.index')));
```

You will see the query string initialises with the values in mount correctly, but instantly after it will append this new query string as described in the first post.

Let me know if there is anything else. 👍

**Comment by tabuna** [comment]
Hey. I just tried your case and couldn't reproduce it. My details:

```php
Route::get('/test', function () {

})->name('component.parent')
    ->breadcrumbs(fn(Trail $trail) => $trail->push('Home'));

Route::get('/component', \App\Http\Livewire\Counter::class)
    ->name('component.index')
    ->breadcrumbs(fn (Trail $trail) => $trail->parent('component.parent')
        ->push('Component Index', route('component.index'))
    );
```

Component code:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    /**
     * @var
     */
    public $month;

    /**
     * @var
     */
    public $year;

    /**
     * @var string[]
     */
    protected $queryString = [
        'month',
        'year'
    ];

    /**
     *
     */
    public function mount()
    {
        $this->month = request()->query('month') ?? 9;
        $this->year = request()->query('year') ?? 2020;
    }

    public function render()
    {
        return view('livewire.counter');
    }
}

```

After navigating to the page, I see breadcrumbs without any errors:

![image](https://user-images.githubusercontent.com/5102591/94353100-bbfc9b80-0075-11eb-8f60-7d4ef61ef43d.png)

What am I doing wrong? Can you show me what needs to be done?

**Comment by zyxxyzyxz** [comment]
@tabuna The breadcrumbs render fine, it's the query string that's the issue. Functionaly speaking the breadcrumbs still function, but it's not ideal having a huge query string be appended. Is this not present in your repro either?

**Comment by tabuna** [comment]
Hey @zyxxyzyxz .
This line is for writing it to the cache when you issue the command `artisan route:cache`
Because with file caching, the actual route declaration code is not executed.

![Снимок экрана 2020-09-28 в 12 33 33](https://user-images.githubusercontent.com/5102591/94416056-0588db80-0187-11eb-8387-d75edae88873.png)

However, this value is deleted immediately after execution, and you will not see this line in the controller.

If this confuses you further, then you can use the breadcrumb definition explicitly rather than in the route.

```php
Breadcrumbs::for('component.index', fn (Trail $trail) =>
    $trail->parent('component.parent')->push('Component Index', route('component.index'))
);
```

With such a record, there will be no lines

**Comment by masterix21** [comment]
I have the same issue using Livewire with tabuna/breadcrumbs

<img width="1028" alt="Schermata 2020-11-10 alle 13 03 51" src="https://user-images.githubusercontent.com/6555012/98671873-36972700-2355-11eb-92b8-fafaa3625a0c.png">

**Comment by masterix21** [comment]
Solved using `Breadcrumb::for(...)` instead of `Route::get(..)->breadcrumb`.

Thanks @tabuna

**Comment by tabuna** [comment]
I guess it depends on the order in which the middleware Livewire is executed before the breadcrumbs?
