### ISSUE TITLE
White space at end of links

### ISSUE THREAD

**Issue by dividy** [tabuna/breadcrumbs#15]
There is a white space displayed at the end of each link inside the breadcrumbs.

This space is caused by the new lines in the view (breadcrumbs.blade.php)

```php
<a href="{{ $crumbs->url() }}">
{{ $crumbs->title() }}
</a>
```

**Comment by tabuna** [comment]
Hey @dividy. Please check the new release

**Comment by dividy** [comment]
Good job and thanks for the quick reply!
