### ISSUE TITLE
Font awesome support

### ISSUE THREAD

**Issue by m-popa** [tabuna/breadcrumbs#26]
Hi Tabuna,

Thanks for the awesome package! 

Is there any support for adding font awesome to breadcrumbs?

**Comment by tabuna** [comment]
Hi @m-popa. You can easily [create your own view](https://github.com/tabuna/breadcrumbs#output-the-breadcrumbs-use-blade-view) using any icons or styles.

**Comment by m-popa** [comment]
Hi @tabuna, Thanks a lot! Really appreciate your help. Cheers!
