### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by abdosaeedelhassan** [tabuna/breadcrumbs#27]
Hi
when i used

 <ul>
                <x-tabuna-breadcrumbs/>
</ul>

i received 502 Bad Gateway, and no error registered in log files, how can i resolve  this or how can i detect the error

thank you

**Comment by tabuna** [comment]
Try using breadcrumbs off-route and at the service provider:

```php
Breadcrumbs::for('photo.index', fn (Trail $trail) =>
    $trail->parent('home')->push('Photos', route('photo.index'))
);
```

**Comment by abdosaeedelhassan** [comment]
@tabuna 
i upgrade to last version and the problem solved, thank you
