### ISSUE TITLE
fail silently?

### ISSUE THREAD

**Issue by jamesj2** [tabuna/breadcrumbs#8]
I'm trying to integrate a legacy application with Laravel.  What I have is a combination of pages, ones that use the new tabuna/breadcrumbs version and some previously written breadcrumbs that are outside of Laravel routes.
 
On my legacy pages where I do not want to use tabuna/breadcrumbs but I still want to use the blade templates.  This is where my issue comes in.  If I call ```Breadcrumbs::current()``` in my layout template I get ```Argument 1 passed to Tabuna\Breadcrumbs\Manager::generate() must be of the type string, null given, called in vendor/tabuna/breadcrumbs/src/Manager.php on line 59```.    Is there a way to fail silently?  Without putting a try/catch block in the blade template?

**Comment by tabuna** [comment]
Hi @jamesj2, 
I understand that some pages just don't have breadcrumbs and you want to use the global template everywhere.
You don't need to wrap any value in try/catch block.
You can check if there are breadcrumbs right now by calling the method:

```php
Breadcrumbs::has();
````


Then you can do it in the following way in your application:

```blade
@includeWhen(Breadcrumbs::has(), 'view.breadcrumbs')
```

```blade
@foreach (Breadcrumbs::current() as $crumbs)
    @if ($crumbs->url() && !$loop->last)
        <li class="breadcrumb-item">
            <a href="{{ $crumbs->url() }}">
                {{ $crumbs->title() }}
            </a>
        </li>
    @else
        <li class="breadcrumb-item active">
            {{ $crumbs->title() }}
        </li>
    @endif
@endforeach
```

**Comment by jamesj2** [comment]
> I understand that some pages just don't have breadcrumbs and you want to use the global template everywhere?

Every page has breadcrumbs but there are two different packages.  Once all the old code has been converted there will only one.  During the transition they share the same layout which is where the breadcrumbs are called.

> You can check if there are breadcrumbs right now by calling the method:
> Breadcrumbs::has();

That works and what I was looking for.   Thanks for your help and examples!
