### ISSUE TITLE
Using Livewire routes macro it push the breadcrumb three times

### ISSUE THREAD

**Issue by masterix21** [tabuna/breadcrumbs#9]
Using the following code in the `web.php` file:

```php
Route::livewire('dashboard', 'dashboard')->name('home')
        ->breadcrumbs(fn (Trail $trail) => $trail->push("Dashboard", route("home")) && \Illuminate\Support\Facades\Log::debug('Dashboard pushed'));
```

You'll get the follow logs output:
```
[2020-09-01 18:25:53] local.DEBUG: Dashboard pushed  
[2020-09-01 18:25:53] local.DEBUG: Dashboard pushed  
[2020-09-01 18:25:53] local.DEBUG: Dashboard pushed  
```

It means that the breadcrumb pushed three times, and the title will be wrong.

**Comment by tabuna** [comment]
Hey @masterix21. Thank you for bringing this to your attention.

I've added a test that verifies this example without using Livewire, and this example only runs once.
Maybe the problem with this behavior is not in this package?

I also have a few questions:
- Is this also called three times with cached routes?
- Is it still a problem to declare breadcrumbs separately from the route?

**Comment by tabuna** [comment]
Hi, I tried to reproduce the problem on the second livewire version. 
But with the code that was recommended.

```php
Route::get('dashboard', \App\Http\Livewire\Counter::class)->name('home')
    ->breadcrumbs(fn (Trail $trail) => $trail->push("Dashboard", route("home")) && \Illuminate\Support\Facades\Log::debug('Dashboard pushed'));
```

This code also works only once.

**Comment by masterix21** [comment]
Using Livewire 2, yes, it works once.

**Comment by tabuna** [comment]
Hey. That's great, then no problem.
